### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/chapel#1]
Overall documentation for building an Exercism track lives at https://exercism.org/docs/building/tracks/new

This issue helps keep track of the tasks you're working on towards launching this track.

The next steps are:

- [x] [Join our community](https://exercism.org/docs/building/tracks/new/join-our-community)
- [x] [Select programming language variant](https://exercism.org/docs/building/tracks/new/select-programming-language-variant) (if applicable)
- [x] [Select testing framework](https://exercism.org/docs/building/tracks/new/select-testing-framework)
- [x] https://github.com/exercism/chapel/issues/3
- [x] #19
- [x] [Fill track docs](https://exercism.org/docs/building/tracks/docs) #10
- [x] [Fill shared files](https://exercism.org/docs/building/tracks/shared-files) #10
- [x] #5
- [x] #53
- [x] [Find Maintainers](https://exercism.org/docs/building/tracks/new/find-maintainers)
- [ ] [Launch!](https://exercism.org/docs/building/tracks/new/launch)
- [x] #38
- [x] [Prepare for open source contributions from strangers](https://exercism.org/docs/building/tracks/new/prepare-for-contributions)

Once you've finished a task, you can check them in this list.

## Questions

Please ask if you have any questions or if anything is confusing!

**Comment by lucaferranti** [comment]
@kytrinyx @ErikSchierboom I am deeply sorry for the loooong break I took. I started the chapel track when starting a new job and got a bit overwhelmed (arguably bad judgemental call from my side for the timing of this project). Anyway, now that my PhD is over and my new job is not new and has stabilized, I can come back to this. I hope to get this launched in the foreseeable future :tada:

**Comment by ErikSchierboom** [comment]
Great! Let me know when we can help.

**Comment by lucaferranti** [comment]
alright Chapel 2.0 has landed !! :tada: 

I'll do a pass of exercises to check they work in 2.0 and update as needed (don't forsee any major blockers) and bump version compatibility to 2.0 here and on the runner.

While I do this, I would expect the syntax highlgiht thing to move forward too, so it's happening folks, it's going to be relased soon!

**Comment by ErikSchierboom** [comment]
Congratulations on the 2.0 release!
